language: ruby

rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.0.x

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile

script: bin/rspec
